services:
  windows:
    image: dockurr/windows
    container_name: windows10ltsc
    environment:
      #VERSION: "ltsc10"
      RAM_SIZE: "4G"
      CPU_CORES: "2"
      # after fresh install = ??GB
      DISK_SIZE: "24G"
      MANUAL: "N"
      USERNAME: "user"
      PASSWORD: "1"
      LANGUAGE: "English"
      REGION: "en-US"
      KEYBOARD: "en-US"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - /docker/dockurr_W10LTSC/_storage_:/storage
      - /docker/dockurr_W10LTSC/shared:/shared
      - /docker/dockurr_W10LTSC/_oem_:/oem
      # ISO size = 4.7GB
      - /docker/_ISO_/win10x64-enterprise-ltsc-eval.iso:/custom.iso

#mkdir -p /docker/dockurr_W10LTSC/_storage_
#mkdir -p /docker/dockurr_W10LTSC/shared
#mkdir -p /docker/dockurr_W10LTSC/_oem_
#chmod -R 777 /docker/dockurr_W10LTSC
